
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("822x483")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 483,
    width = 822,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    822.0,
    490.0,
    fill="#F4ECEC",
    outline="")

canvas.create_text(
    390.0,
    417.0,
    anchor="nw",
    text="OSU\n2023",
    fill="#000000",
    font=("Monospace 16 bold"),
    justify="center"
)

canvas.create_text(
    40.0,
    12.0,
    anchor="nw",
    text="CryptDolphin",
    fill="#000000",
    font=("Monospace 16 bold")
)

image_image_1 = PhotoImage(
    file=relative_to_assets("crypt_icon.png"))
image_1 = canvas.create_image(
    220.0,
    24.0,
    image=image_image_1
)

canvas.create_text(
    260.0,
    77.0,
    anchor="nw",
    text="Шифрование в процессе...",
    fill="#000000",
    font=("Monospace 16 bold")
)
entry_1 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Monospace 8 bold")
)
entry_1.place(
    x=0.0,
    y=155.0,
    width=822.0,
    height=245.0
)
window.resizable(False, False)
window.mainloop()
