
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("374x486")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 486,
    width = 374,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    6.0,
    374.0,
    496.0,
    fill="#F4ECEC",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("arduino_icon.png"))
image_1 = canvas.create_image(
    187.0,
    188.0,
    image=image_image_1
)

canvas.create_text(
    110,
    11.0,
    anchor="nw",
    text="Название",
    fill="#000000",
    font=("Monospace 24")
)

canvas.create_text(
    50.0,
    420.0,
    anchor="nw",
    text="Бесплатно & Безопасно\n2023",
    fill="#000000",
    font=("Monospace 16"),
    justify='center'
)

button_1 = Button(
    text='Подключиться к устройству',
    font=('Monospace 12'),
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)

button_1.place(
    x=50.0,
    y=298.0,
    width=290.0,
    height=34.0
)
window.resizable(False, False)
window.mainloop()
