
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("822x481")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 481,
    width = 822,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    822.0,
    490.0,
    fill="#F4ECEC",
    outline="")

canvas.create_text(
    340.0,
    8.0,
    anchor="nw",
    text="Название",
    fill="#000000",
    font=("Monospace 24 bold")
)

canvas.create_text(
    280.0,
    424.0,
    anchor="nw",
    text="Бесплатно & Безопасно\n2023",
    fill="#000000",
    font=("Monospace 16"),
    justify="center"
)

image_image_1 = PhotoImage(
    file=relative_to_assets("crypt_icon.png"))
image_1 = canvas.create_image(
    124.0,
    227.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("decrypt_icon.png"))
image_2 = canvas.create_image(
    418.0,
    227.0,
    image=image_image_2
)

button_1 = Button(
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
    text="Зашифровать",
    font=("Monospace 12 bold")
)
button_1.place(
    x=68.0,
    y=303.0,
    width=114.0,
    height=38.0
)

button_2 = Button(
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat",
    text="Расшифровать",
    font=("Monospace 12 bold")
)
button_2.place(
    x=339.0,
    y=303.0,
    width=152.0,
    height=44.0
)

button_3 = Button(
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat",
    text="Создать ключ",
    font=("Monospace 12 bold")
)
button_3.place(
    x=622.0,
    y=307.0,
    width=127.0,
    height=44.0
)


image_image_3 = PhotoImage(
    file=relative_to_assets("create_key_icon.png"))
image_3 = canvas.create_image(
    685.0,
    245.0,
    image=image_image_3
)
window.resizable(False, False)
window.mainloop()
