
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("331x486")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 486,
    width = 331,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    326.0,
    490.0,
    fill="#F4ECEC",
    outline="")

canvas.create_text(
    93.0,
    72.0,
    anchor="nw",
    text="Зашифровать",
    fill="#000000",
    font=("Monospace 16")
)

canvas.create_text(
    53.0,
    160.0,
    anchor="nw",
    text="Введите ключ:",
    fill="#000000",
    font=("Monospace 16")
)

entry_bg_1 = canvas.create_image(
    166.5,
    221.5
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=53.0,
    y=205.0,
    width=227.0,
    height=31.0
)

canvas.create_text(
    35.0,
    420.0,
    anchor="nw",
    text="Бесплатно & Безопасно\n2023",
    fill="#000000",
    font=("Monospace 16"),
    justify="center"
)

canvas.create_text(
    85.0,
    11.0,
    anchor="nw",
    text="Название",
    fill="#000000",
    font=("Monospace 24")
)

button_1 = Button(
    text='Зашифровать',
    font=("Monospace 16 bold"),
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=52.0,
    y=272.0,
    width=228.0,
    height=50.0
)
window.resizable(False, False)
window.mainloop()
